require 'asciidoctor'
require 'asciidoctor-diagram'
require 'asciidoctor-revealjs'

outputdir = 'output'
imagesdir = 'images'
revealjs_theme = 'league'
revealjsdir = 'https://cdn.jsdelivr.net/npm/reveal.js@3.9.2'
revealjs_customcss = 'custom.css'

desc 'Cleans and sets up output/slides directory'
task :slidesdirs do
  rm_rf "#{outputdir}/slides"
  mkdir_p "#{outputdir}/slides"
  cp_r "slides/#{imagesdir}", "#{outputdir}/slides/"
  cp "slides/#{revealjs_customcss}", "#{outputdir}/slides/"
end

desc 'Converts slides/*.adoc into reveal.js presentations'
task :slides => [:slidesdirs] do
  files = FileList['slides/*.adoc']
  files.each do |file|
    puts "Converting #{file}..."
    Asciidoctor.convert_file(
      file,
      to_dir: "#{outputdir}/slides",
      backend: 'revealjs',
      safe: :unsafe,
      attributes: "revealjsdir=#{revealjsdir} " + 
                  "revealjs_theme=#{revealjs_theme} " +
                  "imagesdir=#{imagesdir} " +
                  "source-highlighter=rouge " +
                  "customcss=#{revealjs_customcss} " +
                  "icons=font",
    )
  end
end

desc 'Cleans and sets up output/labs directory'
task :labsdirs do
  rm_rf "#{outputdir}/labs"
  mkdir_p "#{outputdir}/labs"
  cp_r "labs/#{imagesdir}", "#{outputdir}/labs/"
end

desc 'Converts labs/*.adoc into HTML5 files'
task :labs => [:labsdirs] do
  files = FileList['labs/*.adoc']
  files.each do |file|
    puts "Converting #{file}..."
    Asciidoctor.convert_file(
      file,
      to_dir: "#{outputdir}/labs",
      backend: 'html5',
      safe: :unsafe,
      attributes: "imagesdir=#{imagesdir} icons=font source-highlighter=rouge",
    )
  end
end

desc 'Deploys the output directory to https://web.njit.edu/~rxt1077/intro_networking'
task :deploy do
  sh "rsync --delete -av #{outputdir}/ rxt1077@afs22.njit.edu:public_html/intro_networking/"
end

desc 'Builds all documents'
task :default => [:slides, :labs]
